2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Configure stats pid to 17580
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Administrator\.config\wandb\settings
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Administrator\Desktop\yolov5-6.0\wandb\settings
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'C:/Users/Administrator/Desktop/yolov5-6.0/train.py'}
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_setup.py:_flush():76] Applying login settings: {'login_timeout': 30}
2023-10-04 10:00:15,501 INFO    MainThread:17580 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Administrator\Desktop\yolov5-6.0\wandb\run-20231004_100015-ouim3cyo\logs\debug.log
2023-10-04 10:00:15,502 INFO    MainThread:17580 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Administrator\Desktop\yolov5-6.0\wandb\run-20231004_100015-ouim3cyo\logs\debug-internal.log
2023-10-04 10:00:15,502 INFO    MainThread:17580 [wandb_init.py:init():547] calling init triggers
2023-10-04 10:00:15,502 INFO    MainThread:17580 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'weights': 'yolov5s.pt', 'cfg': 'C:/Users/Administrator/Desktop/yolov5-6.0/models/yolov5s.yaml', 'data': 'data\\VOC.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.1, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}, 'epochs': 300, 'batch_size': 4, 'imgsz': 640, 'rect': False, 'resume': False, 'nosave': False, 'noval': False, 'noautoanchor': False, 'evolve': None, 'bucket': '', 'cache': None, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'workers': 2, 'project': 'runs\\train', 'name': 'exp', 'exist_ok': False, 'quad': False, 'linear_lr': False, 'label_smoothing': 0.0, 'patience': 100, 'freeze': 0, 'save_period': -1, 'local_rank': -1, 'entity': None, 'upload_dataset': False, 'bbox_interval': -1, 'artifact_alias': 'latest', 'save_dir': 'runs\\train\\exp11'}
2023-10-04 10:00:15,502 INFO    MainThread:17580 [wandb_init.py:init():596] starting backend
2023-10-04 10:00:15,502 INFO    MainThread:17580 [wandb_init.py:init():600] setting up manager
2023-10-04 10:00:15,504 INFO    MainThread:17580 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-10-04 10:00:15,507 INFO    MainThread:17580 [wandb_init.py:init():606] backend started and connected
2023-10-04 10:00:15,509 INFO    MainThread:17580 [wandb_init.py:init():703] updated telemetry
2023-10-04 10:00:15,510 INFO    MainThread:17580 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-10-04 10:01:16,014 ERROR   MainThread:17580 [wandb_init.py:init():762] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-04 10:01:16,077 ERROR   MainThread:17580 [wandb_init.py:init():1170] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\wandb\sdk\wandb_init.py", line 1152, in init
    run = wi.init()
  File "C:\Users\Administrator\anaconda3\envs\yolo\lib\site-packages\wandb\sdk\wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-04 10:01:17,084 WARNING MsgRouterThr:17580 [router.py:message_loop():77] message_loop has been closed
